DROP TABLE USERS;
CREATE TABLE USERS
(
  "ID"         NUMBER            NOT NULL ENABLE,
  "LOGIN"      VARCHAR2(20 BYTE) NOT NULL ENABLE,
  "PASSWORD"   VARCHAR2(20 BYTE) NOT NULL ENABLE,
  "SALT"       VARCHAR2(20 BYTE) NOT NULL ENABLE,
  "FIRST_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
  "LAST_NAME"  VARCHAR2(20 BYTE) NOT NULL ENABLE,
  "DOB"        DATE              NOT NULL ENABLE,
  "EMAIL"      VARCHAR2(20 BYTE) NOT NULL ENABLE,
  CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
);
